[Profile]
Title = BeamNG.drive
Pitch-deadzone = 0
Pitch-inverted = No
Pitch-left-curvature = 0.5
Pitch-right-curvature = 0.5
Pitch-sensitivity = 5
Pitch-left-limit = 80
Pitch-right-limit = 80
Pitch-filter = 0.2
Pitch-enabled = Yes
Yaw-deadzone = 0
Yaw-inverted = No
Yaw-left-curvature = 0.5
Yaw-right-curvature = 0.5
Yaw-sensitivity = 5
Yaw-left-limit = 130
Yaw-right-limit = 130
Yaw-filter = 0.2
Yaw-enabled = Yes
Roll-deadzone = 0
Roll-inverted = No
Roll-left-curvature = 0.5
Roll-right-curvature = 0.5
Roll-sensitivity = 1.5
Roll-left-limit = 45
Roll-right-limit = 45
Roll-filter = 0.2
Roll-enabled = Yes
Xtranslation-deadzone = 0
Xtranslation-inverted = No
Xtranslation-left-curvature = 0.5
Xtranslation-right-curvature = 0.5
Xtranslation-sensitivity = 5
Xtranslation-left-limit = 300
Xtranslation-right-limit = 300
Xtranslation-filter = 0.2
Xtranslation-enabled = Yes
Ytranslation-deadzone = 0
Ytranslation-inverted = No
Ytranslation-left-curvature = 0.5
Ytranslation-right-curvature = 0.5
Ytranslation-sensitivity = 5
Ytranslation-left-limit = 300
Ytranslation-right-limit = 300
Ytranslation-filter = 0.2
Ytranslation-enabled = Yes
Ztranslation-deadzone = 0
Ztranslation-inverted = No
Ztranslation-left-curvature = 0.5
Ztranslation-right-curvature = 0.5
Ztranslation-sensitivity = 2
Ztranslation-left-limit = 300
Ztranslation-right-limit = 1
Ztranslation-filter = 0.5
Ztranslation-enabled = Yes
